_target_: plt_returns.utils.rollout.RolloutWrapper
env_id: PlateletBank
num_env_steps: 365
num_burnin_steps: 100
env_kwargs:
  max_useful_life: ${stock.max_useful_life}
  max_order_quantity: 100
  max_demand: 100
  return_detailed_info: False
env_params:
  poisson_mean_demand_pre_return: ${demand.poisson_mean_demand_pre_return}
  poisson_mean_demand_post_return: ${demand.poisson_mean_demand_post_return}
  slippage: 0.07
  initial_weekday: -1  # Randomly select for each episode
  initial_stock: ${stock.initial_stock}
  age_on_arrival_distributions: ${stock.age_on_arrival_distributions}
  variable_order_cost: -650
  fixed_order_cost: -225
  shortage_cost: -3250
  expiry_cost: -650
  holding_cost: -130
  slippage_cost: -650
  max_steps_in_episode: 365
  return_probability: 0.08
  return_prediction_model_sensitivity: 1
  return_prediction_model_specificity: 1
  gamma: 1.0
return_info: False