_target_: plt_returns.utils.rollout.RolloutWrapper
env_id: PlateletBank
num_env_steps: 365
num_burnin_steps: 100
env_kwargs:
  max_useful_life: 5
  max_order_quantity: 100
  max_demand: 100
  return_detailed_info: False
env_params:
  poisson_mean_demand_pre_return: [14.4, 16.7, 13.1, 14.2, 15.4, 9.3, 9.8]
  poisson_mean_demand_post_return: [14.4, 16.7, 13.1, 14.2, 15.4, 9.3, 9.8]
  slippage: 0.07
  initial_weekday: -1  # Randomly select for each episode
  initial_stock: [0, 0, 0, 0, 0]
  age_on_arrival_distributions: 
    - [0.03, 0.11, 0.28, 0.33, 0.25] # Mon
    - [0.05, 0.13, 0.27, 0.35, 0.20] # Tue
    - [0.04, 0.14, 0.38, 0.18, 0.26] # Wed
    - [0.03, 0.09, 0.05, 0.07, 0.76] # Thu
    - [0.04, 0.03, 0.02, 0.29, 0.62] # Fri
    - [0.00, 0.00, 0.11, 0.28, 0.61] # Sat
    - [0.01, 0.05, 0.19, 0.27, 0.48] # Sun
  variable_order_cost: -650
  fixed_order_cost: -225
  shortage_cost: -3250
  expiry_cost: -650
  holding_cost: -130
  slippage_cost: -650
  max_steps_in_episode: 365
  return_probability: 0.08
  return_prediction_model_sensitivity: 1
  return_prediction_model_specificity: 1
  gamma: 1.0
return_info: False