_target_: plt_returns.utils.rollout.RolloutWrapper
env_id: PlateletBankRealInput
num_env_steps: 365
num_burnin_steps: 0
env_kwargs:
  max_useful_life: ${stock.max_useful_life}
  max_order_quantity: 100
  max_demand: 100
  return_detailed_info: False
  real_input_filepath: /home/joefarrington/CDT/plt_returns/draft_notebooks/example_real_input.csv
  start_date: 2017-01-01
  period_split_hour: 12
env_params:
  slippage: 0.07
  initial_stock: ${stock.initial_stock}
  age_on_arrival_distributions: ${stock.age_on_arrival_distributions}
  variable_order_cost: -650
  fixed_order_cost: -225
  shortage_cost: -3250
  expiry_cost: -650
  holding_cost: -130
  slippage_cost: -650
  max_steps_in_episode: 365
  gamma: 1.0
return_info: True