defaults:
  - rollout_wrapper: platelet_bank_defaults
  - policy: standing_order_policy
  - param_search: grid_sampler
  - _self_

exp_name: plt_returns_temp # Default settings correspond to this experiment

hydra:
  job:
    chdir: True
  run:
    dir: outputs/${exp_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

evaluation:
  seed: 78
  num_rollouts: 10000


