_target_: plt_returns.replenishment_policies.heuristic_policies.standing_order_policy.StandingOrderPolicy
env_id: ${rollout_wrapper.env_id}
env_kwargs: ${rollout_wrapper.env_kwargs}
env_params: ${rollout_wrapper.env_params}