defaults:
  - policy: sS_policy
  - param_search: nsgaii_sampler
  - rollout_wrapper: platelet_bank_defaults
  - _self_

exp_name: plt_returns_temp # Default settings correspond to this experiment

hydra:
  job:
    chdir: True
  run:
    dir: outputs/${exp_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

  searchpath:
    # Search paths assume that run_sim_compare_input...py will be run from sim_compare_input.py
    - file://../conf

evaluation:
  seed: 78
  num_rollouts: 10000

base_demand:
  poisson_mean_demand_pre_return: [13.2, 15.3 , 12.1, 13.0, 14.2,  8.5,  9.0]
  poisson_mean_demand_post_return: [13.2, 15.3 , 12.1, 13.0, 14.2,  8.5,  9.0]

alloc_policies:
  oufo:
    sensitivity: 0.0
    specificity: 1.0
  ppm:
    sensitivity: 1.0
    specificity: 1.0
  
