defaults:
  - policy: standing_order_policy
  - param_search: nsgaii_sampler
  - rollout_wrapper: platelet_bank_defaults
  - demand: uclh_tx
  - stock: uclh
  - _self_

exp_name: plt_returns_temp # Default settings correspond to this experiment

hydra:
  job:
    chdir: True
  run:
    dir: outputs/${exp_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

  searchpath:
    # Search paths assume that run_sim_compare_input...py will be run from sim_compare_input.py
    - file://../conf

evaluation:
  seed: 78
  num_rollouts: 10000

# Base demand is UCLH TX, gets adjusted based on return rate
# Crucial for the sweep over the return rate so that demand for
# units that will be transfused remains the same
base_demand:
  poisson_mean_demand_pre_return: ${demand.poisson_mean_demand_pre_return}
  poisson_mean_demand_post_return: ${demand.poisson_mean_demand_post_return}

issue_policies:
  oufo:
    sensitivity: 0.0
    specificity: 1.0
  ppm:
    sensitivity: 1.0
    specificity: 1.0

param_search:
  early_stopping_rounds: 50
  
