#defaults:
#  - rollout_wrapper: platelet_bank
#  - policy: standing_order_policy
#  - _self_

exp_name: plt_returns_temp # Default settings correspond to this experiment

hydra:
  job:
    chdir: True
  run:
    dir: outputs/${exp_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

#  searchpath:
#    # Search paths assume that run_replenishment_simopt.py will be run from simopt/
#    - file://../scenarios/platelet_bank/conf

param_search:
  sampler:
    _target_: optuna.samplers.GridSampler
  max_parallel_trials: 50
  max_iterations: 100
  num_rollouts: 400
  seed: 10
  search_bounds:
    all_params:
      low: 0
      high: ${rollout_wrapper.env_kwargs.max_order_quantity}

evaluation:
  seed: 78
  num_rollouts: 10000

policy:
  _target_: plt_returns.replenishment_policies.heuristic_policies.standing_order_policy.StandingOrderPolicy
  env_id: ${rollout_wrapper.env_id}
  env_kwargs: ${rollout_wrapper.env_kwargs}
  env_params: ${rollout_wrapper.env_params}

rollout_wrapper:
  _target_: plt_returns.utils.rollout.RolloutWrapper
  env_id: PlateletBank
  num_env_steps: 365
  num_burnin_steps: 100
  env_kwargs:
    max_useful_life: 6
    max_order_quantity: 100
    max_demand: 100
  # For the purposes of this notebook where we may consider different levels of return prob,
  # put in estimate of actual demand for tx (i.e. for UCLH that is estimated as raw x 0.92)
  # And then we scale up the demand by dividing by (1 - return_prob). So we're assuming the same
  # number of people always need to transfused, but there are a verying number of excess orders
  env_params:
    poisson_mean_demand_pre_return: ${base_demand.poisson_mean_demand_pre_return}
    poisson_mean_demand_post_return: ${base_demand.poisson_mean_demand_post_return}
    slippage: 0.0
    initial_weekday: 6  # At the first observation, it is Sunday evening
    initial_stock: [0, 0, 0, 0, 0, 0]
    age_on_arrival_distribution: [0.026, 0.077, 0.173, 0.248, 0.413, 0.063]
    variable_order_cost: -650
    fixed_order_cost: -225
    shortage_cost: -3250
    expiry_cost: -650
    holding_cost: -130
    slippage_cost: -650
    max_steps_in_episode: 365
    return_probability: 0.08 # If return prob zero, base demand is the same as actual demand
    return_prediction_model_sensitivity: 1
    return_prediction_model_specificity: 1
    gamma: 1.0
  return_info: False

base_demand:
  poisson_mean_demand_pre_return: [13.24, 15.32 , 12.09, 13.0456, 14.18,  8.54,  9.04]
  poisson_mean_demand_post_return: [13.24, 15.32 , 12.09, 13.0456, 14.18,  8.54,  9.04]

#scan_over:
#  - name: return_0.00
#    updates:
#      rollout_wrapper:
#        env_params:
#          return_probability: 0.00
#  - name: return_0.05
#    updates:
#      rollout_wrapper:
#        env_params:
#          return_probability: 0.05
#  - name: return_0.10
#    updates:
#      rollout_wrapper:
#        env_params:
#          return_probability: 0.10
#  - name: return_0.15
#    updates:
#      rollout_wrapper:
#        env_params:
#          return_probability: 0.15
#  - name: return_0.20
#    updates:
#      rollout_wrapper:
#        env_params:
#          return_probability: 0.20
#  - name: return_0.25
#    updates:
#      rollout_wrapper:
#        env_params:
#          return_probability: 0.25
#  - name: return_0.30
#    updates:
#      rollout_wrapper:
#        env_params:
#          return_probability: 0.30
# - name: return_0.35
#    updates:
#     rollout_wrapper:
#      env_params:
#          return_probability: 0.35
#  - name: return_0.40
#    updates:
#      rollout_wrapper:
#        env_params:
#          return_probability: 0.40
#  - name: return_0.45
#    updates:
#      rollout_wrapper:
#        env_params:
#          return_probability: 0.45
#  - name: return_0.50
#    updates:
#      rollout_wrapper:
#        env_params:
#          return_probability: 0.50

scan_over:
  - name: slippage_0
    updates:
      rollout_wrapper:
        env_params:
          slippage: 0.0
#  - name: slippage_0.1
#    updates:
#      rollout_wrapper:
#        env_params:
#          slippage: 0.1
  - name: slippage_0.2
    updates:
      rollout_wrapper:
        env_params:
          slippage: 0.2
#  - name: slippage_0.3
#    updates:
#      rollout_wrapper:
#        env_params:
#          slippage: 0.3
  - name: slippage_0.4
    updates:
      rollout_wrapper:
        env_params:
          slippage: 0.4
#  - name: slippage_0.5
#    updates:
#      rollout_wrapper:
#        env_params:
#          slippage: 0.5
  - name: slippage_0.6
    updates:
      rollout_wrapper:
        env_params:
          slippage: 0.6
#  - name: slippage_0.7
#    updates:
#      rollout_wrapper:
#        env_params:
#          slippage: 0.7
  - name: slippage_0.8
    updates:
      rollout_wrapper:
        env_params:
          slippage: 0.8
#  - name: slippage_0.9
#    updates:
#      rollout_wrapper:
#        env_params:
#          slippage: 0.9
  - name: slippage_1.0
    updates:
      rollout_wrapper:
        env_params:
          slippage: 1.0
